# Generated by Django 6.0.7 on 2026-07-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tehnologies',
            new_name='technologies',
        ),
    ]
