# Generated by Django 6.0.7 on 2026-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('PROGRAMMING_LANGUAGE', 'Programming Language'), ('FRAMEWORK', 'Framework'), ('DATABASE', 'Database'), ('TOOL', 'Tool'), ('CLOUD', 'Cloud'), ('DEVOPS', 'DevOps'), ('TESTING', 'Testing')], max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='technologies/icons/')),
                ('website', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
