# Generated by Django 6.0.7 on 2026-07-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING_LANGUAGE', 'Programming Language'), ('FRONT_END', 'Frontend'), ('FRAMEWORK', 'Framework'), ('DATABASE', 'Database'), ('TOOL', 'Tool'), ('CLOUD', 'Cloud'), ('DEVOPS', 'DevOps'), ('TESTING', 'Testing')], max_length=30),
        ),
    ]
