# Generated by Django 6.0.7 on 2026-07-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['full_name'], 'verbose_name_plural': 'Profiles'},
        ),
    ]
